# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LumiWorld' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'MaterialTextField', '~> 0.2'
  pod 'RealmSwift'
  pod 'ESTabBarController-swift'
  pod 'pop'
  pod 'SwifterSwift'
  pod 'IQKeyboardManagerSwift'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'L10n-swift'
  pod 'SCLAlertView'
  pod 'MBProgressHUD'
  pod 'AlamofireImage'
  pod 'NoChat'
  pod 'YYText'
  pod 'HPGrowingTextView'
  pod 'ActionSheetPicker-3.0'
  pod 'Zip', '~> 1.1'
  pod 'VGPlayer', '~> 0.2.0'
  # Pods for LumiWorld

end
