# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LumiWorld' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'MaterialTextField', '~> 0.2'
  pod 'RealmSwift', '~> 3.16.1'
  pod 'ESTabBarController-swift', '~> 2.8.0'
  pod 'pop'
  pod 'SwifterSwift', '~> 5.0'
  pod 'IQKeyboardManagerSwift', '~> 6.5.6'
  pod 'Alamofire', '~> 4.8.2'
  pod 'SwiftyJSON', '~> 5.0'
  pod 'L10n-swift', '~> 5.7.3'
  pod 'SCLAlertView'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'AlamofireImage', '~> 3.5.2'
  pod 'NoChat'
  pod 'YYText'
  pod 'HPGrowingTextView'
  pod 'ActionSheetPicker-3.0', '~> 2.7.1'
  pod 'Zip', '~> 1.1'
  #  pod 'VGPlayer', '~> 0.2.0'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.14.0'
  pod 'YPImagePicker','~> 4.0.0'
  # Pods for LumiWorld
  pod 'Kingfisher', '~> 6.1.1'

end
